USE [BD]
GO

/****** Object:  Table [dbo].[Conta]    Script Date: 20/06/2022 14:09:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Conta](
	[cod] [int] IDENTITY(1,1) NOT NULL,
	[usuario] [nchar](20) NOT NULL,
	[senha] [nchar](50) NOT NULL,
	[tipo] [nchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[cod] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

